services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    volumes:
      - nats:/data
      - ./nsc/nats.conf:/etc/nats/server.conf:ro
      - ./nsc/score/score.jwt:/etc/nats/operator.jwt:ro
    command: ["-c", "/etc/nats/server.conf"]
    networks:
      - internal
      - proxy

  setup:
    depends_on:
      - nats
    build:
      context: ./
      target: server
    restart: no
    volumes:
      - shared:/shared
      - ./scripts/startup.sh:/opt/startup.sh:ro
      - ./nsc/config.json:/opt/config.json:ro
      - ./nsc/creds/score/score/server.creds:/server.creds:ro
      - ./example/checks:/checks:ro
    entrypoint:
      - bash
      - /opt/startup.sh
    networks:
      - internal

  server:
    container_name: server
    depends_on:
      setup:
        condition: service_completed_successfully
    build:
      context: ./
    working_dir: /
    environment:
      NATS_ADDRESS: nats://nats:4222
      NATS_CREDS: /server.creds
    command:
      - server
      - start
      - --db
      - --db-path=/data/results.db
      - --log-level
      - debug
    volumes:
      - ./nsc/config.json:/config.json:ro
      - ./nsc/creds/score/score/server.creds:/server.creds:ro
      - ./outputs/:/data/
    networks:
      - internal
      - proxy

  caddy:
    image: caddy:2.11.4-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/certs:/etc/caddy/certs:ro
    networks:
      - proxy

  agent:
    container_name: agent
    depends_on:
      setup:
        condition: service_completed_successfully
    build:
      context: ./
    volumes:
      - shared:/shared:ro
      - ./nsc/config.json:/opt/config.json:ro
    environment:
      NATS_ADDRESS: nats://localhost:4222
      NATS_CREDS: /shared/agent.creds
    command:
      - agent
      - --teams
      - "0-9"
    network_mode: host

volumes:
  nats:
  caddy_config:
  caddy_data:
  shared:

networks:
  internal:
  proxy:
    external: false
