{{- if .Values.operatorJwt.create }}
apiVersion: v1
kind: Secret
metadata:
  name: score-operator-jwt
  labels:
    {{- include "score.labels" . | nindent 4 }}
type: Opaque
stringData:
  operator.jwt: {{ .Values.operatorJwt.content | quote }}
{{- end }}
