{{- if .Values.serverCreds.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serverCreds.secretName }}
  labels:
    {{- include "score.labels" . | nindent 4 }}
type: Opaque
stringData:
  server.creds: {{ .Values.serverCreds.content | quote }}
{{- end }}
