{{- if .Values.config.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secretName }}
  labels:
    {{- include "score.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: {{ .Values.config.content | quote }}
{{- end }}
