{{- if .Values.server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "score.fullname" . }}-server-data
  labels:
    {{- include "score.labels" . | nindent 4 }}
    {{- include "score.selectorLabels" (dict "component" "server" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.server.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
{{- end }}
