server_name: score
port: 4222

jetstream {
    store_dir: /data/jetstream
    max_memory_store: 268435456   # 256MB
    max_file_store: 1073741824    # 1GB
}

websocket {
    port: 8001
    no_tls: true
}

debug: false
trace: false
logtime: true

operator: /home/nats/.local/share/nats/nsc/stores/score/score.jwt
system_account: SYS_ACCOUNT_ID

resolver {
    type: cache
    dir: '/tmp/jwt'
    ttl: "1h"
    timeout: "1.9s"
}

resolver_preload: {
    SYS_ACCOUNT_ID: SYS_JWT,
    SCORE_ACCOUNT_ID: SCORE_JWT
}
